<!DOCTYPE html>
<html lang="es" xml:lang="es">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4.3 Relación entre varias variables | Análisis de encuestas de hogares con R</title>
  <meta name="description" content="Este es el repositorio del libro Análisis de encuestas con R." />
  <meta name="generator" content="bookdown 0.33 and GitBook 2.6.7" />

  <meta property="og:title" content="4.3 Relación entre varias variables | Análisis de encuestas de hogares con R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Este es el repositorio del libro Análisis de encuestas con R." />
  <meta name="github-repo" content="psirusteam/HHS-Handbook" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4.3 Relación entre varias variables | Análisis de encuestas de hogares con R" />
  
  <meta name="twitter:description" content="Este es el repositorio del libro Análisis de encuestas con R." />
  

<meta name="author" content="Andrés Gutiérrez, Cristian Téllez, Stalyn Guerrero" />


<meta name="date" content="2024-03-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="estimación-puntual.html"/>
<link rel="next" href="análisis-de-variables-categóricas.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Análisis de encuestas de hogares con R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefacio</a></li>
<li class="chapter" data-level="1" data-path="introducción.html"><a href="introducción.html"><i class="fa fa-check"></i><b>1</b> Introducción</a></li>
<li class="chapter" data-level="2" data-path="manejando-una-base-de-encuestas-de-hogares-con-r.html"><a href="manejando-una-base-de-encuestas-de-hogares-con-r.html"><i class="fa fa-check"></i><b>2</b> Manejando una base de encuestas de hogares con <code>R</code></a>
<ul>
<li class="chapter" data-level="2.1" data-path="fundamentos-básicos-de-r-y-rstudio.html"><a href="fundamentos-básicos-de-r-y-rstudio.html"><i class="fa fa-check"></i><b>2.1</b> Fundamentos básicos de <code>R</code> y <code>Rstudio</code></a></li>
<li class="chapter" data-level="2.2" data-path="creación-de-proyectos-en-r.html"><a href="creación-de-proyectos-en-r.html"><i class="fa fa-check"></i><b>2.2</b> Creación de proyectos en <code>R</code></a></li>
<li class="chapter" data-level="2.3" data-path="lectura-de-las-bases-de-datos-y-procesamientos-básicos.html"><a href="lectura-de-las-bases-de-datos-y-procesamientos-básicos.html"><i class="fa fa-check"></i><b>2.3</b> Lectura de las bases de datos y procesamientos básicos</a></li>
<li class="chapter" data-level="2.4" data-path="el-operador-pipeline.html"><a href="el-operador-pipeline.html"><i class="fa fa-check"></i><b>2.4</b> El operador <code>pipeline</code> (%&gt;%)</a></li>
<li class="chapter" data-level="2.5" data-path="creación-de-variables-y-resumen-de-conteos.html"><a href="creación-de-variables-y-resumen-de-conteos.html"><i class="fa fa-check"></i><b>2.5</b> Creación de variables y resumen de conteos</a></li>
<li class="chapter" data-level="2.6" data-path="algunas-estadísticas-descriptivas-sobre-la-base-de-datos.html"><a href="algunas-estadísticas-descriptivas-sobre-la-base-de-datos.html"><i class="fa fa-check"></i><b>2.6</b> Algunas estadísticas descriptivas sobre la base de datos</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="conceptos-básicos-en-encuestas-de-hogares.html"><a href="conceptos-básicos-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>3</b> Conceptos básicos en encuestas de hogares</a>
<ul>
<li class="chapter" data-level="3.1" data-path="unidades-y-marcos-de-muestreo.html"><a href="unidades-y-marcos-de-muestreo.html"><i class="fa fa-check"></i><b>3.1</b> Unidades y marcos de muestreo</a></li>
<li class="chapter" data-level="3.2" data-path="la-base-de-datos-bigcity.html"><a href="la-base-de-datos-bigcity.html"><i class="fa fa-check"></i><b>3.2</b> La base de datos BigCity</a></li>
<li class="chapter" data-level="3.3" data-path="un-esquema-de-muestreo-para-bigcity.html"><a href="un-esquema-de-muestreo-para-bigcity.html"><i class="fa fa-check"></i><b>3.3</b> Un esquema de muestreo para BigCity</a></li>
<li class="chapter" data-level="3.4" data-path="calibración-de-los-factores-de-expansión.html"><a href="calibración-de-los-factores-de-expansión.html"><i class="fa fa-check"></i><b>3.4</b> Calibración de los factores de expansión</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="análisis-de-variables-continuas.html"><a href="análisis-de-variables-continuas.html"><i class="fa fa-check"></i><b>4</b> Análisis de variables continuas</a>
<ul>
<li class="chapter" data-level="4.1" data-path="definición-del-diseño-de-muestreo.html"><a href="definición-del-diseño-de-muestreo.html"><i class="fa fa-check"></i><b>4.1</b> Definición del diseño de muestreo</a></li>
<li class="chapter" data-level="4.2" data-path="estimación-puntual.html"><a href="estimación-puntual.html"><i class="fa fa-check"></i><b>4.2</b> Estimación puntual</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="estimación-puntual.html"><a href="estimación-puntual.html#estimación-de-totales"><i class="fa fa-check"></i><b>4.2.1</b> Estimación de totales</a></li>
<li class="chapter" data-level="4.2.2" data-path="estimación-puntual.html"><a href="estimación-puntual.html#estimación-de-promedios"><i class="fa fa-check"></i><b>4.2.2</b> Estimación de promedios</a></li>
<li class="chapter" data-level="4.2.3" data-path="estimación-puntual.html"><a href="estimación-puntual.html#estimación-de-medidas-de-dispersión-y-localización"><i class="fa fa-check"></i><b>4.2.3</b> Estimación de medidas de dispersión y localización</a></li>
<li class="chapter" data-level="4.2.4" data-path="estimación-puntual.html"><a href="estimación-puntual.html#estimación-del-coeficiente-de-gini"><i class="fa fa-check"></i><b>4.2.4</b> Estimación del coeficiente de Gini</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="relación-entre-varias-variables.html"><a href="relación-entre-varias-variables.html"><i class="fa fa-check"></i><b>4.3</b> Relación entre varias variables</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="relación-entre-varias-variables.html"><a href="relación-entre-varias-variables.html#estimación-de-razones"><i class="fa fa-check"></i><b>4.3.1</b> Estimación de razones</a></li>
<li class="chapter" data-level="4.3.2" data-path="relación-entre-varias-variables.html"><a href="relación-entre-varias-variables.html#prueba-de-hipótesis-para-la-diferencia-de-medias"><i class="fa fa-check"></i><b>4.3.2</b> Prueba de hipótesis para la diferencia de medias</a></li>
<li class="chapter" data-level="4.3.3" data-path="relación-entre-varias-variables.html"><a href="relación-entre-varias-variables.html#contrastes"><i class="fa fa-check"></i><b>4.3.3</b> Contrastes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="análisis-de-variables-categóricas.html"><a href="análisis-de-variables-categóricas.html"><i class="fa fa-check"></i><b>5</b> Análisis de variables categóricas</a>
<ul>
<li class="chapter" data-level="5.1" data-path="definición-del-diseño-de-muestreo-1.html"><a href="definición-del-diseño-de-muestreo-1.html"><i class="fa fa-check"></i><b>5.1</b> Definición del diseño de muestreo</a></li>
<li class="chapter" data-level="5.2" data-path="estimación-puntual-1.html"><a href="estimación-puntual-1.html"><i class="fa fa-check"></i><b>5.2</b> Estimación puntual</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="estimación-puntual-1.html"><a href="estimación-puntual-1.html#estimaciones-de-tamaños"><i class="fa fa-check"></i><b>5.2.1</b> Estimaciones de tamaños</a></li>
<li class="chapter" data-level="5.2.2" data-path="estimación-puntual-1.html"><a href="estimación-puntual-1.html#estimación-de-proporciones"><i class="fa fa-check"></i><b>5.2.2</b> Estimación de proporciones</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="relación-entre-varias-variables-1.html"><a href="relación-entre-varias-variables-1.html"><i class="fa fa-check"></i><b>5.3</b> Relación entre varias variables</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="relación-entre-varias-variables-1.html"><a href="relación-entre-varias-variables-1.html#tablas"><i class="fa fa-check"></i><b>5.3.1</b> Tablas</a></li>
<li class="chapter" data-level="5.3.2" data-path="relación-entre-varias-variables-1.html"><a href="relación-entre-varias-variables-1.html#pruebas-de-independencia"><i class="fa fa-check"></i><b>5.3.2</b> Pruebas de independencia</a></li>
<li class="chapter" data-level="5.3.3" data-path="relación-entre-varias-variables-1.html"><a href="relación-entre-varias-variables-1.html#diferencia-de-proporciones-y-contrastes"><i class="fa fa-check"></i><b>5.3.3</b> Diferencia de proporciones y contrastes</a></li>
<li class="chapter" data-level="5.3.4" data-path="relación-entre-varias-variables-1.html"><a href="relación-entre-varias-variables-1.html#razones-de-odds"><i class="fa fa-check"></i><b>5.3.4</b> Razones de odds</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="análisis-gráfico.html"><a href="análisis-gráfico.html"><i class="fa fa-check"></i><b>6</b> Análisis gráfico</a>
<ul>
<li class="chapter" data-level="6.1" data-path="análisis-gráfico-con-la-librería-survey.html"><a href="análisis-gráfico-con-la-librería-survey.html"><i class="fa fa-check"></i><b>6.1</b> Análisis gráfico con la librería <code>survey</code></a></li>
<li class="chapter" data-level="6.2" data-path="análisis-gráfico-con-la-librería-ggplot2.html"><a href="análisis-gráfico-con-la-librería-ggplot2.html"><i class="fa fa-check"></i><b>6.2</b> Análisis gráfico con la librería <code>ggplot2</code></a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="análisis-gráfico-con-la-librería-ggplot2.html"><a href="análisis-gráfico-con-la-librería-ggplot2.html#definición-del-tema"><i class="fa fa-check"></i><b>6.2.1</b> Definición del tema</a></li>
<li class="chapter" data-level="6.2.2" data-path="análisis-gráfico-con-la-librería-ggplot2.html"><a href="análisis-gráfico-con-la-librería-ggplot2.html#histogramas"><i class="fa fa-check"></i><b>6.2.2</b> Histogramas</a></li>
<li class="chapter" data-level="6.2.3" data-path="análisis-gráfico-con-la-librería-ggplot2.html"><a href="análisis-gráfico-con-la-librería-ggplot2.html#densidades"><i class="fa fa-check"></i><b>6.2.3</b> Densidades</a></li>
<li class="chapter" data-level="6.2.4" data-path="análisis-gráfico-con-la-librería-ggplot2.html"><a href="análisis-gráfico-con-la-librería-ggplot2.html#diagramas-de-caja"><i class="fa fa-check"></i><b>6.2.4</b> Diagramas de caja</a></li>
<li class="chapter" data-level="6.2.5" data-path="análisis-gráfico-con-la-librería-ggplot2.html"><a href="análisis-gráfico-con-la-librería-ggplot2.html#diagramas-de-dispersión"><i class="fa fa-check"></i><b>6.2.5</b> Diagramas de dispersión</a></li>
<li class="chapter" data-level="6.2.6" data-path="análisis-gráfico-con-la-librería-ggplot2.html"><a href="análisis-gráfico-con-la-librería-ggplot2.html#diagrama-de-barras"><i class="fa fa-check"></i><b>6.2.6</b> Diagrama de barras</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="mapas.html"><a href="mapas.html"><i class="fa fa-check"></i><b>6.3</b> Mapas</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="modelos-de-regresión.html"><a href="modelos-de-regresión.html"><i class="fa fa-check"></i><b>7</b> Modelos de regresión</a>
<ul>
<li class="chapter" data-level="7.1" data-path="definiciones-básicas.html"><a href="definiciones-básicas.html"><i class="fa fa-check"></i><b>7.1</b> Definiciones básicas</a></li>
<li class="chapter" data-level="7.2" data-path="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html"><a href="estimación-de-los-parámetros-en-un-modelo-de-regresión-con-muestras-complejas..html"><i class="fa fa-check"></i><b>7.2</b> Estimación de los parámetros en un modelo de regresión con muestras complejas.</a></li>
<li class="chapter" data-level="7.3" data-path="la-ponderación-de-pfeffermann.html"><a href="la-ponderación-de-pfeffermann.html"><i class="fa fa-check"></i><b>7.3</b> La ponderación de Pfeffermann</a></li>
<li class="chapter" data-level="7.4" data-path="diagnóstico-del-modelo.html"><a href="diagnóstico-del-modelo.html"><i class="fa fa-check"></i><b>7.4</b> Diagnóstico del modelo</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="diagnóstico-del-modelo.html"><a href="diagnóstico-del-modelo.html#coeficientes-de-determinación"><i class="fa fa-check"></i><b>7.4.1</b> Coeficientes de determinación</a></li>
<li class="chapter" data-level="7.4.2" data-path="diagnóstico-del-modelo.html"><a href="diagnóstico-del-modelo.html#residuales-estandarizados"><i class="fa fa-check"></i><b>7.4.2</b> Residuales estandarizados</a></li>
<li class="chapter" data-level="7.4.3" data-path="diagnóstico-del-modelo.html"><a href="diagnóstico-del-modelo.html#observaciones-influyentes"><i class="fa fa-check"></i><b>7.4.3</b> Observaciones influyentes</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="inferencia-sobre-los-parámetros-del-modelo.html"><a href="inferencia-sobre-los-parámetros-del-modelo.html"><i class="fa fa-check"></i><b>7.5</b> Inferencia sobre los parámetros del Modelo</a></li>
<li class="chapter" data-level="7.6" data-path="estimación-y-predicción.html"><a href="estimación-y-predicción.html"><i class="fa fa-check"></i><b>7.6</b> Estimación y predicción</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="modelos-lineales-generalizados.html"><a href="modelos-lineales-generalizados.html"><i class="fa fa-check"></i><b>8</b> Modelos lineales generalizados</a>
<ul>
<li class="chapter" data-level="8.1" data-path="modelo-de-regresión-logistica-para-proporciones.html"><a href="modelo-de-regresión-logistica-para-proporciones.html"><i class="fa fa-check"></i><b>8.1</b> Modelo de regresión logistica para proporciones</a></li>
<li class="chapter" data-level="8.2" data-path="modelo-log-lineal-para-tablas-de-contingencia.html"><a href="modelo-log-lineal-para-tablas-de-contingencia.html"><i class="fa fa-check"></i><b>8.2</b> Modelo log-lineal para tablas de contingencia</a></li>
<li class="chapter" data-level="8.3" data-path="modelo-multinomial-para-variables-con-múltiples-categorías.html"><a href="modelo-multinomial-para-variables-con-múltiples-categorías.html"><i class="fa fa-check"></i><b>8.3</b> Modelo multinomial para variables con múltiples categorías</a></li>
<li class="chapter" data-level="8.4" data-path="modelo-gamma-para-variables-continuas-positivas.html"><a href="modelo-gamma-para-variables-continuas-positivas.html"><i class="fa fa-check"></i><b>8.4</b> Modelo Gamma para variables continuas positivas</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="modelos-multinivel.html"><a href="modelos-multinivel.html"><i class="fa fa-check"></i><b>9</b> Modelos multinivel</a>
<ul>
<li class="chapter" data-level="9.1" data-path="modelo-con-intercepto-aleatorio.html"><a href="modelo-con-intercepto-aleatorio.html"><i class="fa fa-check"></i><b>9.1</b> Modelo con intercepto aleatorio</a></li>
<li class="chapter" data-level="9.2" data-path="modelo-con-pendiente-aleatoria.html"><a href="modelo-con-pendiente-aleatoria.html"><i class="fa fa-check"></i><b>9.2</b> Modelo con pendiente aleatoria</a></li>
<li class="chapter" data-level="9.3" data-path="modelo-con-intercepto-y-pendiente-aleatoria.html"><a href="modelo-con-intercepto-y-pendiente-aleatoria.html"><i class="fa fa-check"></i><b>9.3</b> Modelo con intercepto y pendiente aleatoria</a></li>
<li class="chapter" data-level="9.4" data-path="modelo-logístico-multinivel..html"><a href="modelo-logístico-multinivel..html"><i class="fa fa-check"></i><b>9.4</b> Modelo logístico multinivel.</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="imputación-múltiple-en-encuestas-de-hogares.html"><a href="imputación-múltiple-en-encuestas-de-hogares.html"><i class="fa fa-check"></i><b>10</b> Imputación múltiple en encuestas de hogares</a>
<ul>
<li class="chapter" data-level="10.1" data-path="tres-patrones-para-la-ausencia-de-respuesta.html"><a href="tres-patrones-para-la-ausencia-de-respuesta.html"><i class="fa fa-check"></i><b>10.1</b> Tres patrones para la ausencia de respuesta</a></li>
<li class="chapter" data-level="10.2" data-path="imputación-por-la-media-no-condicional..html"><a href="imputación-por-la-media-no-condicional..html"><i class="fa fa-check"></i><b>10.2</b> Imputación por la media no condicional.</a></li>
<li class="chapter" data-level="10.3" data-path="imputación-por-la-media-condicional.html"><a href="imputación-por-la-media-condicional.html"><i class="fa fa-check"></i><b>10.3</b> Imputación por la media condicional</a></li>
<li class="chapter" data-level="10.4" data-path="imputación-por-hot-deck.html"><a href="imputación-por-hot-deck.html"><i class="fa fa-check"></i><b>10.4</b> Imputación por <em>Hot-Deck</em></a></li>
<li class="chapter" data-level="10.5" data-path="imputación-por-regresión.html"><a href="imputación-por-regresión.html"><i class="fa fa-check"></i><b>10.5</b> Imputación por regresión</a></li>
<li class="chapter" data-level="10.6" data-path="imputación-por-el-vecino-más-cercano.html"><a href="imputación-por-el-vecino-más-cercano.html"><i class="fa fa-check"></i><b>10.6</b> Imputación por el vecino más cercano</a></li>
<li class="chapter" data-level="10.7" data-path="imputación-por-el-vecino-más-cercano-con-regresión.html"><a href="imputación-por-el-vecino-más-cercano-con-regresión.html"><i class="fa fa-check"></i><b>10.7</b> Imputación por el vecino más cercano con regresión</a></li>
<li class="chapter" data-level="10.8" data-path="imputación-múltiple..html"><a href="imputación-múltiple..html"><i class="fa fa-check"></i><b>10.8</b> Imputación múltiple.</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="estimación-de-parámetros-para-modelos-en-encuestas-complejas.html"><a href="estimación-de-parámetros-para-modelos-en-encuestas-complejas.html"><i class="fa fa-check"></i><b>11</b> Estimación de parámetros para modelos en encuestas complejas</a>
<ul>
<li class="chapter" data-level="11.1" data-path="acerca-de-las-muestras-aleatorias-y-su-análisis.html"><a href="acerca-de-las-muestras-aleatorias-y-su-análisis.html"><i class="fa fa-check"></i><b>11.1</b> Acerca de las muestras aleatorias y su análisis</a></li>
<li class="chapter" data-level="11.2" data-path="modelos-de-superpoblación.html"><a href="modelos-de-superpoblación.html"><i class="fa fa-check"></i><b>11.2</b> Modelos de superpoblación</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="modelos-de-superpoblación.html"><a href="modelos-de-superpoblación.html#primer-proceso-inferencial-el-modelo"><i class="fa fa-check"></i><b>11.2.1</b> Primer proceso inferencial: el modelo</a></li>
<li class="chapter" data-level="11.2.2" data-path="modelos-de-superpoblación.html"><a href="modelos-de-superpoblación.html#segundo-proceso-inferencial-el-muestreo"><i class="fa fa-check"></i><b>11.2.2</b> Segundo proceso inferencial: el muestreo</a></li>
<li class="chapter" data-level="11.2.3" data-path="modelos-de-superpoblación.html"><a href="modelos-de-superpoblación.html#inferencia-doble-los-modelos-y-el-muestreo"><i class="fa fa-check"></i><b>11.2.3</b> Inferencia doble: los modelos y el muestreo</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="método-de-máxima-verosimilitud.html"><a href="método-de-máxima-verosimilitud.html"><i class="fa fa-check"></i><b>11.3</b> Método de Máxima Verosimilitud</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="método-de-máxima-verosimilitud.html"><a href="método-de-máxima-verosimilitud.html#mv-para-una-distribución-bernoulli"><i class="fa fa-check"></i><b>11.3.1</b> MV para una distribución Bernoulli</a></li>
<li class="chapter" data-level="11.3.2" data-path="método-de-máxima-verosimilitud.html"><a href="método-de-máxima-verosimilitud.html#mv-para-una-distribución-normal"><i class="fa fa-check"></i><b>11.3.2</b> MV para una distribución normal</a></li>
<li class="chapter" data-level="11.3.3" data-path="método-de-máxima-verosimilitud.html"><a href="método-de-máxima-verosimilitud.html#mv-para-una-regresión-lineal-múltiple"><i class="fa fa-check"></i><b>11.3.3</b> MV para una regresión lineal múltiple</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="método-de-máxima-pseudo-verosimilitud.html"><a href="método-de-máxima-pseudo-verosimilitud.html"><i class="fa fa-check"></i><b>11.4</b> Método de Máxima Pseudo-Verosimilitud</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="método-de-máxima-pseudo-verosimilitud.html"><a href="método-de-máxima-pseudo-verosimilitud.html#mpv-para-una-distribución-bernoulli"><i class="fa fa-check"></i><b>11.4.1</b> MPV para una distribución Bernoulli</a></li>
<li class="chapter" data-level="11.4.2" data-path="método-de-máxima-pseudo-verosimilitud.html"><a href="método-de-máxima-pseudo-verosimilitud.html#mpv-para-una-distribución-normal"><i class="fa fa-check"></i><b>11.4.2</b> MPV para una distribución normal</a></li>
<li class="chapter" data-level="11.4.3" data-path="método-de-máxima-pseudo-verosimilitud.html"><a href="método-de-máxima-pseudo-verosimilitud.html#mpv-para-una-regresión-múltiple"><i class="fa fa-check"></i><b>11.4.3</b> MPV para una regresión múltiple</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a Análisis de encuestas de hogares con R </a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Análisis de encuestas de hogares con R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="relación-entre-varias-variables" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Relación entre varias variables<a href="relación-entre-varias-variables.html#relación-entre-varias-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En muchos análisis de variables relacionadas con encuestas de hogares no solo basta con analizar el comportamiento de variables de manera individual, por ejemplo, ingresos medios de hombres y mujeres en un país sino también, analizar la diferencia entre los ingresos de los hombres y las mujeres. Esto último con el fin de ir cerrando la brecha salarial que existe. En esta sección se darán las herramientas computacionales para estimar razones y se estudiarán las pruebas de hipótesis para diferencia de medias, junto con contrastes más complejos.</p>
<div id="estimación-de-razones" class="section level3 hasAnchor" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> Estimación de razones<a href="relación-entre-varias-variables.html#estimación-de-razones" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Un caso particular de una función no lineal de totales es la razón poblacional. Esta se define como el cociente de dos totales poblacionales de características de interés de tipo continuo. En las encuestas de hogares, en ocasiones se requiere estimar este parámetro, por ejemplo, la razón entre los gastos y los ingresos, la cantidad de hombres por cada mujer o la cantidad de mascotas por cada hogar en un país determinado. Puesto que la razón es un cociente de totales, tanto en numerador como el denominador son cantidades desconocidas y por tanto requieren estimarse. El estimador puntual de una razón en muestreos complejos equivale al cociente de los estimadores de los totales como se define a continuación:</p>
<p><span class="math display">\[\begin{eqnarray}
\hat{R}_{\omega}  =  \frac{\hat{y}_{\omega}}{\hat{x}_{\omega}}
  =  \frac{{ \sum_{h=1}^{H}\sum_{\alpha=1}^{\alpha_{h}}\sum_{i=1}^{nh\alpha}}\omega_{h\alpha i}y_{h\alpha i}}{{ \sum_{h=1}^{H}\sum_{\alpha=1}^{\alpha_{h}}\sum_{i=1}^{nh\alpha}}\omega_{h\alpha i}x_{h\alpha i}}
\end{eqnarray}\]</span></p>
<p>Sin embargo, dado que estimador de la razón es un cociente entre dos estimadores, es decir, un cociente de dos variables aleatorias, el cálculo de la estimación de la varianza no es sencillo de obtener. Para ellos, se debe aplicar linealización de Taylor como lo muestra <span class="citation">Gutiérrez (<a href="#ref-Gutierrez_2016">2016</a>)</span>.</p>
<p>La función <code>survey_ratio</code> tiene implementado los procedimientos para estimar las razones y sus varianzas. Para un correcto cálculo de la estimación de la razón y su varianza estimada se debe introducir en la función el numerador de la razón (<code>numerator</code>) y el denominador (<code>denominator</code>). Adicional a esto, se debe indicar el nivel de confianza de los intervalos. A continuación, se muestran los códigos computacionales para estimar la razón entre el gasto y el ingreso.</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="relación-entre-varias-variables.html#cb131-1" tabindex="-1"></a>diseno <span class="sc">%&gt;%</span></span>
<span id="cb131-2"><a href="relación-entre-varias-variables.html#cb131-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Razon =</span>  <span class="fu">survey_ratio</span>(</span>
<span id="cb131-3"><a href="relación-entre-varias-variables.html#cb131-3" tabindex="-1"></a>    <span class="at">numerator =</span> Expenditure,</span>
<span id="cb131-4"><a href="relación-entre-varias-variables.html#cb131-4" tabindex="-1"></a>    <span class="at">denominator =</span> Income,</span>
<span id="cb131-5"><a href="relación-entre-varias-variables.html#cb131-5" tabindex="-1"></a>    <span class="at">level =</span> <span class="fl">0.95</span>,</span>
<span id="cb131-6"><a href="relación-entre-varias-variables.html#cb131-6" tabindex="-1"></a>    <span class="at">vartype =</span>  <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>)</span>
<span id="cb131-7"><a href="relación-entre-varias-variables.html#cb131-7" tabindex="-1"></a>  ))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 4
##   Razon Razon_se Razon_low Razon_upp
##   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 0.649   0.0232     0.603     0.695</code></pre>
<p>Como se puede observar, la razón entre el gasto y el ingreso se estima en 0.64. Lo que implica que por cada unidad 100 unidades monetarias que le ingrese al hogar, se gastan 64 unidades, consiguiendo un intervalo de confianza al 95% de 0.60 y 0.69. Si el objetivo es estimar la razón entre mujeres y hombres , se realiza de la siguiente manera:</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="relación-entre-varias-variables.html#cb133-1" tabindex="-1"></a>diseno <span class="sc">%&gt;%</span></span>
<span id="cb133-2"><a href="relación-entre-varias-variables.html#cb133-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Razon =</span>  <span class="fu">survey_ratio</span>(</span>
<span id="cb133-3"><a href="relación-entre-varias-variables.html#cb133-3" tabindex="-1"></a>    <span class="at">numerator =</span> (Sex <span class="sc">==</span> <span class="st">&quot;Female&quot;</span>),</span>
<span id="cb133-4"><a href="relación-entre-varias-variables.html#cb133-4" tabindex="-1"></a>    <span class="at">denominator =</span> (Sex <span class="sc">==</span> <span class="st">&quot;Male&quot;</span>),</span>
<span id="cb133-5"><a href="relación-entre-varias-variables.html#cb133-5" tabindex="-1"></a>    <span class="at">level =</span> <span class="fl">0.95</span>,</span>
<span id="cb133-6"><a href="relación-entre-varias-variables.html#cb133-6" tabindex="-1"></a>    <span class="at">vartype =</span>  <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>)</span>
<span id="cb133-7"><a href="relación-entre-varias-variables.html#cb133-7" tabindex="-1"></a>  ))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 4
##   Razon Razon_se Razon_low Razon_upp
##   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1  1.11   0.0351      1.04      1.18</code></pre>
<p>Como la variable sexo en la base de datos es una variable categórica, se tuvo la necesidad de generar las variables indicadores (<em>dummies</em>) para su cálculo; <code>Sex == "Female"</code> para el caso de las mujeres y <code>Sex == "Male"</code> para el caso de los hombres. Los resultados del ejercicio anterior muestran que en la base de datos hay más mujeres que hombres, generando una razón de 1.11. Esto significa que, por cada 100 hombres hay aproximadamente 111 mujeres con un intervalo que varía entre 1.04 y 1.18.</p>
<p>Si se desea hacer la razón de mujeres y hombres pero en la zona rural, se haría de la siguiente manera:</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="relación-entre-varias-variables.html#cb135-1" tabindex="-1"></a>sub_Rural <span class="sc">%&gt;%</span></span>
<span id="cb135-2"><a href="relación-entre-varias-variables.html#cb135-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Razon =</span>  <span class="fu">survey_ratio</span>(</span>
<span id="cb135-3"><a href="relación-entre-varias-variables.html#cb135-3" tabindex="-1"></a>    <span class="at">numerator =</span> (Sex <span class="sc">==</span> <span class="st">&quot;Female&quot;</span>),</span>
<span id="cb135-4"><a href="relación-entre-varias-variables.html#cb135-4" tabindex="-1"></a>    <span class="at">denominator =</span> (Sex <span class="sc">==</span> <span class="st">&quot;Male&quot;</span>),</span>
<span id="cb135-5"><a href="relación-entre-varias-variables.html#cb135-5" tabindex="-1"></a>    <span class="at">level =</span> <span class="fl">0.95</span>,</span>
<span id="cb135-6"><a href="relación-entre-varias-variables.html#cb135-6" tabindex="-1"></a>    <span class="at">vartype =</span>  <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>)</span>
<span id="cb135-7"><a href="relación-entre-varias-variables.html#cb135-7" tabindex="-1"></a>  ))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 4
##   Razon Razon_se Razon_low Razon_upp
##   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1  1.07   0.0352     0.997      1.14</code></pre>
<p>Obteniendo nuevamente que hay más mujeres que hombres. Ahora bien, otro análisis de interés es estimar la razón de gastos pero solo en la población femenina. A continuación, se presentan los códigos computacionales.</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="relación-entre-varias-variables.html#cb137-1" tabindex="-1"></a>sub_Mujer <span class="sc">%&gt;%</span></span>
<span id="cb137-2"><a href="relación-entre-varias-variables.html#cb137-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Razon =</span>  <span class="fu">survey_ratio</span>(</span>
<span id="cb137-3"><a href="relación-entre-varias-variables.html#cb137-3" tabindex="-1"></a>    <span class="at">numerator =</span> Expenditure,</span>
<span id="cb137-4"><a href="relación-entre-varias-variables.html#cb137-4" tabindex="-1"></a>    <span class="at">denominator =</span> Income,</span>
<span id="cb137-5"><a href="relación-entre-varias-variables.html#cb137-5" tabindex="-1"></a>    <span class="at">level =</span> <span class="fl">0.95</span>,</span>
<span id="cb137-6"><a href="relación-entre-varias-variables.html#cb137-6" tabindex="-1"></a>    <span class="at">vartype =</span>  <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>)</span>
<span id="cb137-7"><a href="relación-entre-varias-variables.html#cb137-7" tabindex="-1"></a>  ))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 4
##   Razon Razon_se Razon_low Razon_upp
##   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 0.658   0.0199     0.619     0.698</code></pre>
<p>Dando como resultado que por cada 100 unidades monetarias que le ingresan a las mujeres se gastan 65 con un intervalo de confianza entre 0.61 y 0.69. Por último, análogamente para los hombres, la razón de gastos resulta muy similar que para las mujeres.</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="relación-entre-varias-variables.html#cb139-1" tabindex="-1"></a>sub_Hombre <span class="sc">%&gt;%</span></span>
<span id="cb139-2"><a href="relación-entre-varias-variables.html#cb139-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Razon =</span>  <span class="fu">survey_ratio</span>(</span>
<span id="cb139-3"><a href="relación-entre-varias-variables.html#cb139-3" tabindex="-1"></a>    <span class="at">numerator =</span> Expenditure,</span>
<span id="cb139-4"><a href="relación-entre-varias-variables.html#cb139-4" tabindex="-1"></a>    <span class="at">denominator =</span> Income,</span>
<span id="cb139-5"><a href="relación-entre-varias-variables.html#cb139-5" tabindex="-1"></a>    <span class="at">level =</span> <span class="fl">0.95</span>,</span>
<span id="cb139-6"><a href="relación-entre-varias-variables.html#cb139-6" tabindex="-1"></a>    <span class="at">vartype =</span>  <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>)</span>
<span id="cb139-7"><a href="relación-entre-varias-variables.html#cb139-7" tabindex="-1"></a>  ))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 4
##   Razon Razon_se Razon_low Razon_upp
##   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 0.639   0.0288     0.582     0.696</code></pre>
</div>
<div id="prueba-de-hipótesis-para-la-diferencia-de-medias" class="section level3 hasAnchor" number="4.3.2">
<h3><span class="header-section-number">4.3.2</span> Prueba de hipótesis para la diferencia de medias<a href="relación-entre-varias-variables.html#prueba-de-hipótesis-para-la-diferencia-de-medias" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Se le llama prueba de hipótesis a un procedimiento estadístico utilizado para evaluar la evidencia en favor o en contra de una afirmación o suposición acerca de una población. En este proceso, se plantea una hipótesis nula (<span class="math inline">\(H_0\)</span>), que representa la afirmación inicial que debe ser probada, y una hipótesis alternativa (<span class="math inline">\(H_1\)</span>), que es la afirmación contraria a la hipótesis nula. Esta afirmación puede estar basada en alguna creencia o experiencia pasada que será contrastada con la evidencia que se obtengan a través de la información contenida en la muestra. Si se sospecha que el parámetro <span class="math inline">\(\theta\)</span> es igual a cierto valor particular <span class="math inline">\(\theta_{0}\)</span>, las posible combinaciones de hipótesis que se pueden contrastar son:</p>
<p><span class="math display">\[\begin{eqnarray*}
\begin{cases}
H_{0}: &amp; \theta=\theta_{0}\\
H_{1}: &amp; \theta\neq\theta_{0}
\end{cases}\,\,\,\,\,\,\,\,\,   
\begin{cases}
H_{0}: &amp; \theta=\theta_{0}\\
H_{1}: &amp; \theta&gt;\theta_{0}
\end{cases}\,\,\,\,\,\,\,\,\,   
\begin{cases}
H_{0}: &amp; \theta=\theta_{0}\\
H_{1}: &amp; \theta&lt;\theta_{0}
\end{cases}
\end{eqnarray*}\]</span></p>
<p>Se dirá que una de las dos hipótesis es cierta sólo si la evidencia estadística, la cual es obtenida de la muestra, la apoya. El proceso por medio del cual se escoge una de las dos hipótesis es llamado Prueba de Hipótesis.</p>
<p>En términos generales, algunos parámetros importantes se pueden escribir como una combinación lineal de medidas de interés. Los casos más usuales son diferencias de medias, sumas ponderadas de medias utilizadas para construir índices económicos, etc. De esta forma, considere una función que es una combinación lineal de <span class="math inline">\(j\)</span> estadísticas descriptivas como se muestra a continuación:</p>
<p><span class="math display">\[\begin{eqnarray*}
f\left(\theta_{1},\theta_{2},...,\theta_{j}\right) &amp; = &amp; \sum_{j=1}^{J}a_{j}\theta_{j}
\end{eqnarray*}\]</span></p>
<p>En <span class="math inline">\(a_{j}\)</span> son constantes conocidas. Un estimador de esta función está dado por:</p>
<p><span class="math display">\[\begin{eqnarray}
\hat{f}_{\omega}\left(\hat{\theta}_{1},\hat{\theta}_{2},...,\hat{\theta}_{j}\right) &amp; = &amp; \sum_{j=1}^{J}a_{j}\hat{\theta}_{j}
\end{eqnarray}\]</span></p>
<p>Y su varianza se calcula como sigue:</p>
<p><span class="math display">\[\begin{eqnarray}
var\left(\sum_{j=1}^{J}a_{j}\hat{\theta}_{j}\right) &amp; = &amp; \sum_{j=1}^{J}a_{j}^{2}var\left(\hat{\theta}_{j}\right)+2\times\sum_{j=1}^{J-1}\sum_{k&gt;j}^{J}a_{j}a_{k}\,cov\left(\hat{\theta}_{j},\hat{\theta}_{k}\right)
\end{eqnarray}\]</span></p>
<p>Como se pudo observar en la ecuación de la varianza del estimador, esta incorpora las varianzas de las estimaciones de todos los componentes individuales, así como las covarianzas de los pares estimados.</p>
<p>Es de nuestro particular interés analizar la diferencia de medias poblacionales, que se puede escribir como sigue:</p>
<p><span class="math display">\[
\bar{y}^{1}-\bar{y}^{2}
\]</span></p>
<p>En donde, <span class="math inline">\(\bar{y}_{1}\)</span> es la media de la primera población, por ejemplo, ingresos medios en los hogares obtenido por los padres de familia y <span class="math inline">\(\bar{y}_{2}\)</span> es la media de la segunda población, que para seguir el ejemplo serían, los ingresos medios de las madres en un hogar. Este parámetro puede ser estimado insesgadamente por:</p>
<p><span class="math display">\[
\hat{\bar{y}}_{\omega}^{1}-\hat{\bar{y}}_{\omega}^{2}
\]</span></p>
<p>En donde <span class="math inline">\(\hat{\bar{y}}_{\omega}^{i}\)</span> es el estimador de muestreo de <span class="math inline">\(\bar{y}^{i}\)</span> (<span class="math inline">\(i = 1, 2.\)</span>). Considerando el parámetro de interés en esta sección, las hipótesis a estudiar serían las siguientes:</p>
<p><span class="math display">\[\begin{eqnarray*}
\begin{cases}
H_{0}:\bar{y}_{1}-\bar{y}_{2}=0\\
H_{1}:\bar{y}_{1}-\bar{y}_{2}\neq0
\end{cases} &amp; \begin{cases}
H_{0}:\bar{y}_{1}-\bar{y}_{2}=0\\
H_{1}:\bar{y}_{1}-\bar{y}_{2}&gt;0
\end{cases} &amp; \begin{cases}
H_{0}:\bar{y}_{1}-\bar{y}_{2}=0\\
H_{1}:\bar{y}_{1}-\bar{y}_{2}&lt;0
\end{cases}
\end{eqnarray*}\]</span></p>
<p>Para probar estas hipótesis se utiliza el siguiente estadístico de prueba, el cual tiene distribución t-student con <span class="math inline">\(gl\)</span> grados de libertad, los cuales están dados por la diferencia entre el número de UPM y el número de estratos.</p>
<p><span class="math display">\[
t = \frac{\hat{\bar{y}}_{\omega}^{1}-\hat{\bar{y}}_{\omega}^{2}}{se\left(\bar{y}_{1}-\bar{y}_{2}\right)} \sim t_{gl}
\]</span></p>
<p>donde,</p>
<p><span class="math display">\[
\widehat{se}\left(\hat{\bar{y}}_{\omega}^{1}-\hat{\bar{y}}_{\omega}^{2}\right) = \sqrt{\widehat{var}\left(\hat{\bar{y}}_{\omega}^{1}\right) + \widehat{var}\left(\hat{\bar{y}}_{\omega}^{2}\right) - 2 \  \widehat{cov}\left(\hat{\bar{y}}_{\omega}^{1},\hat{\bar{y}}_{\omega}^{2}\right)}
\]</span></p>
<p>Si se desea construir un intervalo de confianza para la diferencia de media se realizaría de la siguiente manera:</p>
<p><span class="math display">\[
\hat{\bar{y}}_{\omega}^{1}-\hat{\bar{y}}_{\omega}^{2} \pm t_{gl}\ \widehat{se}\left(\hat{\bar{y}}_{\omega}^{1}-\hat{\bar{y}}_{\omega}^{2}\right)
\]</span></p>
<p>Para poder llevar a cabo la prueba de hipótesis para la diferencia de media de los ingresos en un hogar por sexo, tomemos la base de datos que tenemos como ejemplo. La función que se encarga de realizar la prueba es <code>svyttest</code> y solo requiere como argumentos la variable ingreso (o variable de interés), la variable sexo (variable discriminadora), el diseño muestral y el nivel de confianza. A continuación, se muestran los códigos computacionales que se requieren:</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="relación-entre-varias-variables.html#cb141-1" tabindex="-1"></a><span class="fu">svyttest</span>(Income <span class="sc">~</span> Sex, <span class="at">design =</span> diseno, <span class="at">level =</span> <span class="fl">0.95</span>) </span></code></pre></div>
<pre><code>## 
##  Design-based t-test
## 
## data:  Income ~ Sex
## t = 1.3625, df = 118, p-value = 0.1756
## alternative hypothesis: true difference in mean is not equal to 0
## 95 percent confidence interval:
##  -12.82205  69.38503
## sample estimates:
## difference in mean 
##           28.28149</code></pre>
<p>En esta salida podemos observar que el p-valor de la prueba es 0.17. Si tomamos una significancia del 5% para la prueba se puede concluir que, con una confianza del 95% y basados en la muestra, no existe suficiente evidencia estadística para decir que los ingresos medios en los hogares son diferentes por sexo. Por otro lado, el intervalo de confianza al 95% para la diferencia de medias entre los ingresos de hombres y mujeres es <span class="math inline">\(\left(-12.8,\,69.3\right)\)</span>.</p>
<p>Si ahora el objetivo es realizar la prueba de diferencia de medias para los ingresos entre hombres y mujeres pero solo en la zona urbana, los códigos computacionales son los siguientes:</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="relación-entre-varias-variables.html#cb143-1" tabindex="-1"></a><span class="fu">svyttest</span>(Income <span class="sc">~</span> Sex, <span class="at">design =</span> sub_Urbano, <span class="at">level =</span> <span class="fl">0.95</span>) </span></code></pre></div>
<pre><code>## 
##  Design-based t-test
## 
## data:  Income ~ Sex
## t = 1.5667, df = 63, p-value = 0.1222
## alternative hypothesis: true difference in mean is not equal to 0
## 95 percent confidence interval:
##  -12.31754 101.74023
## sample estimates:
## difference in mean 
##           44.71134</code></pre>
<p>En donde, al igual que el anterior, no se rechaza la hipótesis nula con una confianza del 95%. Por otro lado, la función <code>svyttest</code> permite usar filtros. Si se requiere probar la hipótesis de diferencia de medias de ingresos por sexo pero solo en aquellas personas del hogar mayores a 18 años, se utilizará dentro de la función <code>svyttest</code> la función <code>filter</code> como se muestra a continuación:</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="relación-entre-varias-variables.html#cb145-1" tabindex="-1"></a><span class="fu">svyttest</span>(Income <span class="sc">~</span> Sex,</span>
<span id="cb145-2"><a href="relación-entre-varias-variables.html#cb145-2" tabindex="-1"></a>         <span class="at">design =</span> diseno <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Age <span class="sc">&gt;</span> <span class="dv">18</span>),</span>
<span id="cb145-3"><a href="relación-entre-varias-variables.html#cb145-3" tabindex="-1"></a>         <span class="at">level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## 
##  Design-based t-test
## 
## data:  Income ~ Sex
## t = 1.5263, df = 118, p-value = 0.1296
## alternative hypothesis: true difference in mean is not equal to 0
## 95 percent confidence interval:
##  -10.72746  82.85253
## sample estimates:
## difference in mean 
##           36.06253</code></pre>
<p>y con una confianza del 95% y basado en la muestra tampoco se rechaza la hipótesis hula. Es decir, no existe evidencia estadística para concluir que los ingresos medios entre hombres y mujeres mayores de 18 años son diferentes.</p>
</div>
<div id="contrastes" class="section level3 hasAnchor" number="4.3.3">
<h3><span class="header-section-number">4.3.3</span> Contrastes<a href="relación-entre-varias-variables.html#contrastes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En muchas ocasiones, se requiere comparar más de dos poblaciones al mismo tiempo; por ejemplo, comparar los ingresos medios de los hogares en tres regiones con el fin de identificar aquellas regiones donde hubo un mayor impacto en los hogares. En casos como estos la diferencia de medias que estudiamos en capítulos anteriores no es suficiente dado que permite solo comprar parejas de poblaciones y por ende que, hacer contraste resulta una muy buena alternativa para abordar este tipo de problemas.</p>
<p>Recurriendo en las definiciones que se han trabajado en este capítulo, un contraste es una combinación lineal de parámetros de la forma:</p>
<p><span class="math display">\[\begin{eqnarray*}
f = A * \theta = f\left(\theta^{1},\theta^{2},...,\theta^{j}\right) &amp; = &amp; \sum_{j=1}^{J}a_{j}\theta^{j}
\end{eqnarray*}\]</span></p>
<p>En donde <span class="math inline">\(A\)</span> es una matriz o vector de constantes y <span class="math inline">\(\theta\)</span> es una matriz o vector de parámetros. Los procedimientos metodológicos para implementar los contrastes en diseños de muestreo complejos están desarrolladas en la función <code>svycontrast</code>. A continuación, se muestra el uso de dicha función para el cálculo de contraste en la base de datos de ejemplo, comparando el promedio de ingresos por región. Como primer ejemplo, se realizará la comparación de dos poblaciones, las regiones Norte y Sur. En particular, es de interés la diferencia de ingresos (<span class="math inline">\(f = \bar{y}^{Norte} - \bar{y}^{Sur}\)</span>). Puesto que la población tiene cinco regiones y solo se construirá el contraste para dos de ellas (la región Norte y la región Sur), este queda definido de la siguiente manera:</p>
<p><span class="math display">\[\begin{eqnarray*}
f = A * \theta  = 1\times{\bar{y}}^{Norte}+\left(-1\right)\times{\bar{y}}^{Sur}+0\times{\bar{y}}^{Centro}+0\times{\bar{y}}^{Occidente}+0\times{\bar{y}}^{Oriente}
\end{eqnarray*}\]</span></p>
<p>Como se puede observar, en este caso el vector de contraste es <span class="math inline">\(A = \left[1,\,-1,\,0,\,0,\,0\right]\)</span>. De forma matricial, el estimador de este contraste específico queda definido de la siguiente manera:</p>
<p><span class="math display">\[\begin{eqnarray*}
\hat{f}_{\omega} = A * \hat{\theta} = \left[1,\,-1,\,0,\,0,\,0\right]\times\left[\begin{array}{c}
\hat{\bar{y}}^{Norte}_{\omega}\\
\hat{\bar{y}}^{Sur}_{\omega}\\
\hat{\bar{y}}^{Centro}_{\omega}\\
\hat{\bar{y}}^{Occidente}_{\omega}\\
\hat{\bar{y}}^{Oriente}_{\omega}
\end{array}\right]
\end{eqnarray*}\]</span></p>
<p>Ahora bien, para realizar procesos de la construcción del estimador del contraste y su varianza estimada paso a paso se procede a calcular las medias estimadas por región con la función <code>svyby</code> como se muestra a continuación:</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="relación-entre-varias-variables.html#cb147-1" tabindex="-1"></a>prom_region <span class="ot">&lt;-</span> <span class="fu">svyby</span>(</span>
<span id="cb147-2"><a href="relación-entre-varias-variables.html#cb147-2" tabindex="-1"></a>  <span class="at">formula =</span> <span class="sc">~</span> Income,</span>
<span id="cb147-3"><a href="relación-entre-varias-variables.html#cb147-3" tabindex="-1"></a>  <span class="at">by =</span> <span class="sc">~</span> Region,</span>
<span id="cb147-4"><a href="relación-entre-varias-variables.html#cb147-4" tabindex="-1"></a>  <span class="at">design =</span> diseno,</span>
<span id="cb147-5"><a href="relación-entre-varias-variables.html#cb147-5" tabindex="-1"></a>  <span class="at">FUN =</span> svymean,</span>
<span id="cb147-6"><a href="relación-entre-varias-variables.html#cb147-6" tabindex="-1"></a>  <span class="at">na.rm =</span> T,</span>
<span id="cb147-7"><a href="relación-entre-varias-variables.html#cb147-7" tabindex="-1"></a>  <span class="at">covmat =</span> <span class="cn">TRUE</span>,</span>
<span id="cb147-8"><a href="relación-entre-varias-variables.html#cb147-8" tabindex="-1"></a>  <span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>)</span>
<span id="cb147-9"><a href="relación-entre-varias-variables.html#cb147-9" tabindex="-1"></a>)</span>
<span id="cb147-10"><a href="relación-entre-varias-variables.html#cb147-10" tabindex="-1"></a></span>
<span id="cb147-11"><a href="relación-entre-varias-variables.html#cb147-11" tabindex="-1"></a>prom_region</span></code></pre></div>
<pre><code>##              Region   Income       se     ci_l     ci_u
## Norte         Norte 552.3637 55.35987 443.8603 660.8670
## Sur             Sur 625.7740 62.40574 503.4610 748.0870
## Centro       Centro 650.7820 61.46886 530.3053 771.2588
## Occidente Occidente 517.0071 46.22077 426.4161 607.5982
## Oriente     Oriente 541.7543 71.66487 401.2938 682.2149</code></pre>
<p>La función <code>svyby</code> permite aplicar una función, en este caso la media (<code>svymean</code>) por región (<code>by</code>) utilizando el diseño muestral complejo de la encuesta (<code>design</code>). Las demás componentes de la función ya se han utilizado previamente. Como resultado de aplicar esta función se obtienen las medias estimadas de los ingresos por región. Para continuar con el ejemplo, se tomarán solo los ingresos medios estimados de las regiones Norte y Sur y calcularemos su diferencia:</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="relación-entre-varias-variables.html#cb149-1" tabindex="-1"></a><span class="co"># Paso 1: diferencia de estimaciones (Norte - Sur) </span></span>
<span id="cb149-2"><a href="relación-entre-varias-variables.html#cb149-2" tabindex="-1"></a><span class="fl">552.4</span> <span class="sc">-</span> <span class="fl">625.8</span></span></code></pre></div>
<pre><code>## [1] -73.4</code></pre>
<p>El paso siguiente es calcular la matriz de varianzas y covarianzas y de allí extraer las varianzas y covarianzas de las regiones Norte y Sur:</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="relación-entre-varias-variables.html#cb151-1" tabindex="-1"></a><span class="co"># Paso 2: Matriz de varianzas y covarianzas</span></span>
<span id="cb151-2"><a href="relación-entre-varias-variables.html#cb151-2" tabindex="-1"></a><span class="fu">vcov</span>(prom_region)</span></code></pre></div>
<pre><code>##              Norte      Sur  Centro Occidente  Oriente
## Norte     3064.715    0.000    0.00     0.000    0.000
## Sur          0.000 3894.476    0.00     0.000    0.000
## Centro       0.000    0.000 3778.42     0.000    0.000
## Occidente    0.000    0.000    0.00  2136.359    0.000
## Oriente      0.000    0.000    0.00     0.000 5135.854</code></pre>
<p>Como el muestreo es independiente en cada región, las covarianzas en la anterior matriz son nulas. Para calcular el error estándar de la diferencia (contraste) se usará las propiedades de la varianza, puesto que:</p>
<p><span class="math display">\[
se(\hat{f}_{\omega}) = se\left(\hat{\bar{y}}^{Norte}_{\omega}-\hat{\bar{y}}^{Sur}_{\omega}\right)=\sqrt{var\left(\hat{\bar{y}}^{Norte}_{\omega}\right)+var\left(\hat{\bar{y}}^{Sur}_{\omega}\right)-2\,cov\left(\hat{\bar{y}}^{Norte}_{\omega},\hat{\bar{y}}^{Sur}_{\omega}\right)}
\]</span></p>
<p>Por tanto, tenemos que el error estándar estimado para este contraste es:</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="relación-entre-varias-variables.html#cb153-1" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="dv">3065</span> <span class="sc">+</span> <span class="dv">3894</span> <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## [1] 83.42062</code></pre>
<p>Ahora bien, la función <code>svycontrast</code> devuelve el contraste estimado y su error estándar. Los argumentos de esta función son los promedios de los ingresos estimados (<code>stat</code>) y las constantes de contraste (<code>contrasts</code>). Se obtiene como resultado que la diferencia de los ingresos medios se estima en 73.4 unidades monetarias con un error estándar de 83.42 unidades.</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="relación-entre-varias-variables.html#cb155-1" tabindex="-1"></a><span class="fu">svycontrast</span>(<span class="at">stat =</span> prom_region, </span>
<span id="cb155-2"><a href="relación-entre-varias-variables.html#cb155-2" tabindex="-1"></a>            <span class="at">contrasts =</span> <span class="fu">list</span>(<span class="at">diff_NS =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>)))</span></code></pre></div>
<pre><code>##         contrast     SE
## diff_NS   -73.41 83.422</code></pre>
<p>Por otro lado, es posible ampliar la estructura de los contrastes. Por ejemplo, considere que se quieren estimar los siguientes contrastes:</p>
<ul>
<li><span class="math inline">\(\bar{y}^{Norte} - \bar{y}^{Centro}\)</span>,</li>
<li><span class="math inline">\(\bar{y}^{Sur}-\bar{y}^{Centro}\)</span>,</li>
<li><span class="math inline">\(\bar{y}^{Occidente}-\bar{y}^{Oriente}\)</span></li>
</ul>
<p>En este caso, la matriz de contrastes escrita de forma matricial tendría la siguiente estructura:</p>
<p><span class="math display">\[
A =
\left[\begin{array}{ccccc}
1 &amp; 0 &amp; -1 &amp; 0 &amp; 0\\
0 &amp; 1 &amp; -1 &amp; 0 &amp; 0\\
0 &amp; 0 &amp; 0 &amp; 1 &amp; -1
\end{array}\right]
\]</span></p>
<p>Ahora, aplicando la función <code>svycontrast</code> en <code>R</code> se obtiene:</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="relación-entre-varias-variables.html#cb157-1" tabindex="-1"></a><span class="fu">svycontrast</span>(</span>
<span id="cb157-2"><a href="relación-entre-varias-variables.html#cb157-2" tabindex="-1"></a>  <span class="at">stat =</span> prom_region,</span>
<span id="cb157-3"><a href="relación-entre-varias-variables.html#cb157-3" tabindex="-1"></a>  <span class="at">contrasts =</span> <span class="fu">list</span>(</span>
<span id="cb157-4"><a href="relación-entre-varias-variables.html#cb157-4" tabindex="-1"></a>    <span class="at">Norte_sur =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb157-5"><a href="relación-entre-varias-variables.html#cb157-5" tabindex="-1"></a>    <span class="at">Sur_centro =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb157-6"><a href="relación-entre-varias-variables.html#cb157-6" tabindex="-1"></a>    <span class="at">Occidente_Oriente =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb157-7"><a href="relación-entre-varias-variables.html#cb157-7" tabindex="-1"></a>  )</span>
<span id="cb157-8"><a href="relación-entre-varias-variables.html#cb157-8" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>##                   contrast     SE
## Norte_sur          -98.418 82.723
## Sur_centro         -25.008 87.595
## Occidente_Oriente  -24.747 85.277</code></pre>
<p>También es posible construir contrastes en dominios que estén correlacionadas. Por ejemplo, Ingreso y Sexo. Como se hizo en el ejemplo anterior, se inicia con el promedio estimado por sexo.</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="relación-entre-varias-variables.html#cb159-1" tabindex="-1"></a>prom_sexo <span class="ot">&lt;-</span> <span class="fu">svyby</span>(</span>
<span id="cb159-2"><a href="relación-entre-varias-variables.html#cb159-2" tabindex="-1"></a>  <span class="at">formula =</span> <span class="sc">~</span> Income,</span>
<span id="cb159-3"><a href="relación-entre-varias-variables.html#cb159-3" tabindex="-1"></a>  <span class="at">by =</span> <span class="sc">~</span> Sex,</span>
<span id="cb159-4"><a href="relación-entre-varias-variables.html#cb159-4" tabindex="-1"></a>  <span class="at">design =</span> diseno,</span>
<span id="cb159-5"><a href="relación-entre-varias-variables.html#cb159-5" tabindex="-1"></a>  <span class="at">FUN =</span> svymean,</span>
<span id="cb159-6"><a href="relación-entre-varias-variables.html#cb159-6" tabindex="-1"></a>  <span class="at">na.rm =</span> T,</span>
<span id="cb159-7"><a href="relación-entre-varias-variables.html#cb159-7" tabindex="-1"></a>  <span class="at">covmat =</span> <span class="cn">TRUE</span>,</span>
<span id="cb159-8"><a href="relación-entre-varias-variables.html#cb159-8" tabindex="-1"></a>  <span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>)</span>
<span id="cb159-9"><a href="relación-entre-varias-variables.html#cb159-9" tabindex="-1"></a>)</span>
<span id="cb159-10"><a href="relación-entre-varias-variables.html#cb159-10" tabindex="-1"></a></span>
<span id="cb159-11"><a href="relación-entre-varias-variables.html#cb159-11" tabindex="-1"></a>prom_sexo</span></code></pre></div>
<pre><code>##           Sex   Income       se     ci_l     ci_u
## Female Female 557.5681 25.82995 506.9423 608.1939
## Male     Male 585.8496 34.58759 518.0592 653.6400</code></pre>
<p>Si el contraste de interés es <span class="math inline">\(\theta = \bar{y}^{F} - \bar{y}^{M}\)</span>, entonces usando la función <code>svycontrast</code> se obtiene el contraste estimado, junto con su error estándar, obteniendo como resultado que, en promedio, los hombres obtienen 28.3 unidades monetarias más que las mujeres con una error estándar de 20.76.</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="relación-entre-varias-variables.html#cb161-1" tabindex="-1"></a><span class="fu">svycontrast</span>(<span class="at">stat =</span> prom_sexo,</span>
<span id="cb161-2"><a href="relación-entre-varias-variables.html#cb161-2" tabindex="-1"></a>            <span class="at">contrasts =</span> <span class="fu">list</span>(<span class="at">diff_Sexo =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>)))</span></code></pre></div>
<pre><code>##           contrast     SE
## diff_Sexo  -28.281 20.756</code></pre>
<p>Más aún, otra posibilidad es poder obtener resultados agregados, por ejemplo, con sumas de totales en regiones:</p>
<p><span class="math display">\[
\hat{f}_{\omega}=\hat{y}^{Norte}_{\omega}+\hat{y}^{Sur}_{\omega} +\hat{y}^{Centro}_{\omega}
\]</span></p>
<p>En este caso, se crea la función adecuada con sumas de totales por regiones</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="relación-entre-varias-variables.html#cb163-1" tabindex="-1"></a>sum_region <span class="ot">&lt;-</span> <span class="fu">svyby</span>(</span>
<span id="cb163-2"><a href="relación-entre-varias-variables.html#cb163-2" tabindex="-1"></a>  <span class="sc">~</span> Income,</span>
<span id="cb163-3"><a href="relación-entre-varias-variables.html#cb163-3" tabindex="-1"></a>  <span class="sc">~</span> Region,</span>
<span id="cb163-4"><a href="relación-entre-varias-variables.html#cb163-4" tabindex="-1"></a>  diseno,</span>
<span id="cb163-5"><a href="relación-entre-varias-variables.html#cb163-5" tabindex="-1"></a>  svytotal,</span>
<span id="cb163-6"><a href="relación-entre-varias-variables.html#cb163-6" tabindex="-1"></a>  <span class="at">na.rm =</span> T,</span>
<span id="cb163-7"><a href="relación-entre-varias-variables.html#cb163-7" tabindex="-1"></a>  <span class="at">covmat =</span> <span class="cn">TRUE</span>,</span>
<span id="cb163-8"><a href="relación-entre-varias-variables.html#cb163-8" tabindex="-1"></a>  <span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>)</span>
<span id="cb163-9"><a href="relación-entre-varias-variables.html#cb163-9" tabindex="-1"></a>)</span>
<span id="cb163-10"><a href="relación-entre-varias-variables.html#cb163-10" tabindex="-1"></a></span>
<span id="cb163-11"><a href="relación-entre-varias-variables.html#cb163-11" tabindex="-1"></a>sum_region</span></code></pre></div>
<pre><code>##              Region   Income      se     ci_l     ci_u
## Norte         Norte 14277323 1507575 11322530 17232115
## Sur             Sur 16068151 1877989 12387359 19748942
## Centro       Centro 16483319 2383556 11811634 21155003
## Occidente Occidente 16853540 1823807 13278944 20428135
## Oriente     Oriente 22111335 2833460 16557856 27664814</code></pre>
<p>Para este caso en particular, la matriz de contraste queda como:
<span class="math display">\[
\left[\begin{array}{cccccc}
1 &amp; 1 &amp; 1 &amp; 0 &amp; 0
\end{array}\right]
\]</span></p>
<p>Una vez más, el procedimiento en <code>R</code> es como sigue:</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="relación-entre-varias-variables.html#cb165-1" tabindex="-1"></a><span class="fu">svycontrast</span>(<span class="at">stat =</span> sum_region,</span>
<span id="cb165-2"><a href="relación-entre-varias-variables.html#cb165-2" tabindex="-1"></a>            <span class="at">contrasts =</span> <span class="fu">list</span>(<span class="at">Agregado_NCS =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>))) </span></code></pre></div>
<pre><code>##              contrast      SE
## Agregado_NCS 46828792 3388357</code></pre>
<p>Por último, si se desean obtener los promedios por categorías. Por ejemplo:</p>
<p><span class="math display">\[
\hat{f} = \hat{\bar{y}}_{Edad} = \frac{1}{J}\sum_{j=1}^J\hat{\bar{y}}_{j}
\]</span></p>
<p>donde <span class="math inline">\(K\)</span> es el número de categorías de la variable. En <code>R</code> se hace de la siguiente manera:</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="relación-entre-varias-variables.html#cb167-1" tabindex="-1"></a>prom_edad <span class="ot">&lt;-</span> <span class="fu">svyby</span>(</span>
<span id="cb167-2"><a href="relación-entre-varias-variables.html#cb167-2" tabindex="-1"></a>  <span class="at">formula =</span> <span class="sc">~</span> Income,</span>
<span id="cb167-3"><a href="relación-entre-varias-variables.html#cb167-3" tabindex="-1"></a>  <span class="at">by =</span> <span class="sc">~</span> CatAge,</span>
<span id="cb167-4"><a href="relación-entre-varias-variables.html#cb167-4" tabindex="-1"></a>  <span class="at">design =</span>  diseno,</span>
<span id="cb167-5"><a href="relación-entre-varias-variables.html#cb167-5" tabindex="-1"></a>  <span class="at">FUN =</span> svymean,</span>
<span id="cb167-6"><a href="relación-entre-varias-variables.html#cb167-6" tabindex="-1"></a>  <span class="at">na.rm =</span> T,</span>
<span id="cb167-7"><a href="relación-entre-varias-variables.html#cb167-7" tabindex="-1"></a>  <span class="at">covmat =</span> <span class="cn">TRUE</span></span>
<span id="cb167-8"><a href="relación-entre-varias-variables.html#cb167-8" tabindex="-1"></a>)</span>
<span id="cb167-9"><a href="relación-entre-varias-variables.html#cb167-9" tabindex="-1"></a></span>
<span id="cb167-10"><a href="relación-entre-varias-variables.html#cb167-10" tabindex="-1"></a>prom_edad</span></code></pre></div>
<pre><code>##              CatAge   Income       se
## 0-5             0-5 463.7715 28.86795
## 6-15           6-15 511.6179 34.88031
## 16-30         16-30 607.2917 37.41561
## 31-45         31-45 573.4167 26.94744
## 46-60         46-60 763.0610 58.97170
## Más de 60 Más de 60 466.6133 31.20795</code></pre>
<p>Cuyo vector de contraste estaría dada por:</p>
<p><span class="math display">\[
A =
\left[\begin{array}{cccccc}
\frac{1}{6} &amp; \frac{1}{6} &amp; \frac{1}{6} &amp; \frac{1}{6} &amp; \frac{1}{6} &amp; \frac{1}{6}
\end{array}\right]
\]</span></p>
<p>El procedimiento en <code>R</code> es:</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="relación-entre-varias-variables.html#cb169-1" tabindex="-1"></a><span class="fu">svycontrast</span>(<span class="at">stat =</span> prom_edad,</span>
<span id="cb169-2"><a href="relación-entre-varias-variables.html#cb169-2" tabindex="-1"></a>            <span class="at">contrasts =</span> <span class="fu">list</span>(<span class="at">agregado_edad =</span></span>
<span id="cb169-3"><a href="relación-entre-varias-variables.html#cb169-3" tabindex="-1"></a>                               <span class="fu">rep</span>(<span class="dv">1</span> <span class="sc">/</span> <span class="dv">6</span>, <span class="at">times =</span> <span class="dv">6</span>)))</span></code></pre></div>
<pre><code>##               contrast     SE
## agregado_edad    564.3 25.404</code></pre>
<p>También es posible realizar contrastes con parámetros más complejos, como por ejemplo razones. Considere la diferencia por sexo entre las razones de gastos contra ingresos. En primer lugar se debe crear la función que permita estimar las razones por sexo:</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="relación-entre-varias-variables.html#cb171-1" tabindex="-1"></a>razon_sexo <span class="ot">&lt;-</span> <span class="fu">svyby</span>(</span>
<span id="cb171-2"><a href="relación-entre-varias-variables.html#cb171-2" tabindex="-1"></a>  <span class="at">formula =</span> <span class="sc">~</span> Income,</span>
<span id="cb171-3"><a href="relación-entre-varias-variables.html#cb171-3" tabindex="-1"></a>  <span class="at">by =</span> <span class="sc">~</span> Sex,</span>
<span id="cb171-4"><a href="relación-entre-varias-variables.html#cb171-4" tabindex="-1"></a>  <span class="at">denominator =</span> <span class="sc">~</span> Expenditure,</span>
<span id="cb171-5"><a href="relación-entre-varias-variables.html#cb171-5" tabindex="-1"></a>  <span class="at">design =</span> diseno,</span>
<span id="cb171-6"><a href="relación-entre-varias-variables.html#cb171-6" tabindex="-1"></a>  <span class="at">FUN =</span> svyratio,</span>
<span id="cb171-7"><a href="relación-entre-varias-variables.html#cb171-7" tabindex="-1"></a>  <span class="at">na.rm =</span> T,</span>
<span id="cb171-8"><a href="relación-entre-varias-variables.html#cb171-8" tabindex="-1"></a>  <span class="at">covmat =</span> <span class="cn">TRUE</span>,</span>
<span id="cb171-9"><a href="relación-entre-varias-variables.html#cb171-9" tabindex="-1"></a>  <span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>)</span>
<span id="cb171-10"><a href="relación-entre-varias-variables.html#cb171-10" tabindex="-1"></a>)</span>
<span id="cb171-11"><a href="relación-entre-varias-variables.html#cb171-11" tabindex="-1"></a></span>
<span id="cb171-12"><a href="relación-entre-varias-variables.html#cb171-12" tabindex="-1"></a>razon_sexo</span></code></pre></div>
<pre><code>##           Sex Income/Expenditure se.Income/Expenditure     ci_l     ci_u
## Female Female           1.519060            0.04582607 1.429243 1.608878
## Male     Male           1.564762            0.07044239 1.426698 1.702827</code></pre>
<p>Luego, la estimación de la diferencia de razones, estaría dada por el siguiente contraste, en donde se puede concluir que la diferencia de las razones es estimada en 0.045 en favor de los hombres.</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="relación-entre-varias-variables.html#cb173-1" tabindex="-1"></a><span class="fu">svycontrast</span>(<span class="at">stat =</span> razon_sexo,</span>
<span id="cb173-2"><a href="relación-entre-varias-variables.html#cb173-2" tabindex="-1"></a>            <span class="at">contrasts =</span> <span class="fu">list</span>(<span class="at">diff_sexo =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>))) </span></code></pre></div>
<pre><code>##            contrast     SE
## diff_sexo -0.045702 0.0416</code></pre>

</div>
</div>
<!-- </div> -->
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-Gutierrez_2016" class="csl-entry">
———. 2016. <em>Estrategias de muestreo: diseño de encuestas y estimación de parámetros</em>. Segunda edición. Ediciones de la U.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="estimación-puntual.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="análisis-de-variables-categóricas.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/psirusteam/LibroAEHR/04-Continuas.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Análisis de encuestas de hogares con R.pdf", "Análisis de encuestas de hogares con R.epub", "Análisis de encuestas de hogares con R.mobi"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
},
"tconfig": null
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
